/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wei_hook_MainActivity */

#ifndef _Included_com_wei_hook_MainActivity
#define _Included_com_wei_hook_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wei_hook_MainActivity
 * Method:    getAppID
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wei_hook_MainActivity_getAppID
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
